const movieReviewData = [
  [
    {
      id: "m1",
      title: "Inception",
      content: "Mind bending movie, Nolan never disappoints!",
      rating: 5,
      by: "Rahim U",
      on: 1718500000001,
    },
    {
      id: "m1",
      title: "Inception",
      content: "Story complex but খুব interesting",
      rating: 4,
      by: "Sabbir H",
      on: 1718500000002,
    },
  ],
  [
    {
      id: "m2",
      title: "Titanic",
      content: "Emotional rollercoaster 😢",
      rating: 5,
      by: "Mitu A",
      on: 1718500000003,
    },
    {
      id: "m2",
      title: "Titanic",
      content: "Classic love story",
      rating: 4,
      by: "Jamal K",
      on: 1718500000004,
    },
    {
      id: "m2",
      title: "Titanic",
      content: "A bit slow but worth it",
      rating: 4,
      by: "Nadia S",
      on: 1718500000005,
    },
  ],
  [
    {
      id: "m3",
      title: "The Dark Knight",
      content: "Best Batman movie ever",
      rating: 5,
      by: "Hasan R",
      on: 1718500000006,
    },
    {
      id: "m3",
      title: "The Dark Knight",
      content: "Joker performance 🔥",
      rating: 5,
      by: "Imran T",
      on: 1718500000007,
    },
  ],
  [
    {
      id: "m4",
      title: "Avatar",
      content: "Visual masterpiece",
      rating: 5,
      by: "Rupa D",
      on: 1718500000008,
    },
    {
      id: "m4",
      title: "Avatar",
      content: "Story average but visuals amazing",
      rating: 4,
      by: "Kamal P",
      on: 1718500000009,
    },
    {
      id: "m4",
      title: "Avatar",
      content: "Loved Pandora world",
      rating: 5,
      by: "Tanvir M",
      on: 1718500000010,
    },
  ],
  [
    {
      id: "m5",
      title: "Joker",
      content: "Dark and গভীর movie",
      rating: 5,
      by: "Arif L",
      on: 1718500000011,
    },
  ],
  [
    {
      id: "m6",
      title: "Frozen",
      content: "Kids friendly and fun",
      rating: 4,
      by: "Sumi K",
      on: 1718500000012,
    },
    {
      id: "m6",
      title: "Frozen",
      content: "Songs are catchy 🎶",
      rating: 5,
      by: "Nusrat J",
      on: 1718500000013,
    },
  ],
  [
    {
      id: "m7",
      title: "Spider-Man: No Way Home",
      content: "Nostalgia overloaded 🔥",
      rating: 5,
      by: "Rakib Z",
      on: 1718500000014,
    },
    {
      id: "m7",
      title: "Spider-Man: No Way Home",
      content: "Fan service done right",
      rating: 5,
      by: "Shanto B",
      on: 1718500000015,
    },
    {
      id: "m7",
      title: "Spider-Man: No Way Home",
      content: "Too many characters but fun",
      rating: 4,
      by: "Nayeem F",
      on: 1718500000016,
    },
  ],
  [
    {
      id: "m8",
      title: "The Matrix",
      content: "Ahead of its time",
      rating: 5,
      by: "Fahim S",
      on: 1718500000017,
    },
    {
      id: "m8",
      title: "The Matrix",
      content: "Concept is mind blowing",
      rating: 5,
      by: "Rasel D",
      on: 1718500000018,
    },
  ],
  [
    {
      id: "m9",
      title: "Harry Potter",
      content: "Magical journey ✨",
      rating: 5,
      by: "Labib A",
      on: 1718500000019,
    },
    {
      id: "m9",
      title: "Harry Potter",
      content: "Childhood favorite",
      rating: 5,
      by: "Nabil H",
      on: 1718500000020,
    },
    {
      id: "m9",
      title: "Harry Potter",
      content: "Rewatchable series",
      rating: 4,
      by: "Sadia T",
      on: 1718500000021,
    },
  ],
  [
    {
      id: "m10",
      title: "Fast & Furious",
      content: "Action packed 🚗💨",
      rating: 4,
      by: "Bappi G",
      on: 1718500000022,
    },
    {
      id: "m10",
      title: "Fast & Furious",
      content: "Story weak but action great",
      rating: 3,
      by: "Kawsar M",
      on: 1718500000023,
    },
  ],
];

export function getMovieReviewData() {
  return movieReviewData;
}
